app:
  port: 8080
  log_level: "debug"

db:
  host:     "0.0.0.0"
  port:     "5432"
  user:     "user"
  password: "password"
  db_name:  "db"
  ssl_mode: "disable"

jwt:
  secret_key:      "1234"
  expiration_time: "24h"

prometheus:
  host: "localhost:9090"
  job_name: ""
