app:
  port: 8080
  log_level: "debug"

db:
  host:     "193.108.113.9"
  port:     "5432"
  user:     "postgres"
  password: "mygame1f9d1111"
  db_name:  "my_game"
  ssl_mode: "disable"

jwt:
  secret_key:      "1234"
  expiration_time: "24h"

monitoring:
  pushURL: "127.0.0.1:9091"
  username: prometheus
  password: prometheus
  jobName: mygame
  instanceName: metrics
